import PDFDocument from "pdfkit";
import { Resend } from "resend";

export default async function handler(req, res) {

  if (req.method !== "GET") {
    return res.status(405).json({
      success: false,
      error: "Method not allowed"
    });
  }

  try {

    const resendApiKey = process.env.RESEND_API_KEY;

    if (!resendApiKey) {
      return res.status(500).json({
        success: false,
        error: "RESEND_API_KEY is not configured."
      });
    }

    const applicationId =
      "TEST-" +
      new Date().getFullYear() +
      "-" +
      Date.now().toString().slice(-6);

    const doc = new PDFDocument({
      margin: 50
    });

    const chunks = [];

    doc.on("data", (chunk) => {
      chunks.push(chunk);
    });

    const pdfReady = new Promise((resolve, reject) => {
      doc.on("end", resolve);
      doc.on("error", reject);
    });

    doc.fontSize(22)
      .text("VASWAN FILMS", {
        align: "center"
      });

    doc.moveDown();

    doc.fontSize(18)
      .text("KON BANEGA KING", {
        align: "center"
      });

    doc.moveDown();

    doc.fontSize(14)
      .text("TEST CASTING APPLICATION", {
        align: "center"
      });

    doc.moveDown(2);

    doc.fontSize(11);

    doc.text(`Application ID: ${applicationId}`);
    doc.text("Applicant Name: Test Applicant");
    doc.text("Application Fee: INR 199");
    doc.text("Payment Status: TEST");

    doc.moveDown();

    doc.text("This is a test PDF generated by VASWAN FILMS.");

    doc.moveDown(2);

    doc.text(
      "Email and PDF delivery system test completed."
    );

    doc.moveDown(2);

    doc.text(
      "Presented by VASWAN FILMS",
      {
        align: "center"
      }
    );

    doc.end();

    await pdfReady;

    const pdfBuffer = Buffer.concat(chunks);

    const resend = new Resend(resendApiKey);

    const { data, error } = await resend.emails.send({

      from: "VASWAN FILMS <casting@vaswanfilms.in>",

      to: [
        "comadykrishna4@gmail.com",
        "Vaswankrishna@gmail.com"
      ],

      subject: "VASWAN FILMS - Test Application PDF",

      html: `
        <h2>VASWAN FILMS - Email Test</h2>

        <p>This is a test email for the Kon Banega King application system.</p>

        <p><strong>PDF:</strong> Test application PDF is attached.</p>

        <p><strong>Status:</strong> Email system working.</p>
      `,

      attachments: [
        {
          filename: `${applicationId}.pdf`,
          content: pdfBuffer
        }
      ]

    });

    if (error) {

      console.error("Resend Error:", error);

      return res.status(500).json({
        success: false,
        error: error.message || "Email could not be sent."
      });

    }

    return res.status(200).json({
      success: true,
      application_id: applicationId,
      message: "Test PDF created and email sent successfully."
    });

  } catch (error) {

    console.error("Test Email Error:", error);

    return res.status(500).json({
      success: false,
      error: error.message || "Test email failed."
    });

  }
}
